### ISSUE TITLE
error in fetch

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [abhishekpal1993/script-fetch-next-tech-courses#1]
![image](https://user-images.githubusercontent.com/69203685/91844663-7f57a300-ec75-11ea-9cb3-7baa20251769.png)

Can you help me.

**Comment by abhishekpal1993** [comment]
Yah sure, sorry about the incomplete error messages. Looks like the data param is not an array in extractData function.

Possible reasons:
1] You don't have any course defined
2] Mostly likely the secret-token is incorrect. You need to use the token from the next-tech admin panel.

**Comment by Siddharth-Selvarajan** [comment]
Thanks for your support. Where can i get my token? or Secret Key?

**Comment by abhishekpal1993** [comment]
As mentioned in my previous comment, this secret key is to be generated by team over admin panel.
For business, teams will have team memebers who will create contents. Normal users can access these contents when they are published.
Each team will have its own secret key. This secret key is not usually found over webpage. Its a configuration usually stored at the backend preferably. What you maybe seeing over webpages are tokens, which expire in 24 hours or so depending on the configurations.

For more information on teams and business check this documentation - https://docs.next.tech/account-management/for-businesses

**Comment by Siddharth-Selvarajan** [comment]
ok, thanks for your support.
